Design
carystokes/cookie_monstah pull request #14
Opened 2016-10-07 19:08 UTC by larisabainton

2016-10-07 19:22 UTC, nwalberts commented on app/assets/stylesheets/colors.scss
> +$light-grey: #D3D3D3;
address this

2016-10-07 19:22 UTC, nwalberts commented on app/assets/stylesheets/application.scss
> +  padding: 1rem;
not required, but suggested you reorder

2016-10-07 19:23 UTC, nwalberts commented on app/assets/stylesheets/show.scss
> +    font-color: $medium-grey
address this

2016-10-11 15:05 UTC, jraenorris requested changes
Did you mean to upload the cookie image?

2016-10-11 15:05 UTC, jraenorris commented on app/assets/stylesheets/application.scss
> +    text-decoration: none;
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/assets/stylesheets/application.scss
> +    text-decoration: none;
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/assets/stylesheets/index.scss
> +  padding: 1rem;
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/assets/stylesheets/index.scss
> +    padding: 1rem;
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/assets/stylesheets/index.scss
> +  color: $white;
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/assets/stylesheets/show.scss
> +    float: right;
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/models/review.rb
> +  inclusion: {
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/models/review.rb
> +  inclusion: {
Address all hound violations. If you update the .yml to address them, make a reply on the hound comments

2016-10-11 15:05 UTC, jraenorris commented on app/views/recipes/show.html.erb
> +<<<<<<< HEAD
Looks like this is the remains of a merge conflict?

2016-10-11 15:05 UTC, jraenorris commented on app/views/recipes/show.html.erb
> +    <br>
It's better practice to nest things in `<p>` tags rather than tossing in `<br />` tags here and there

2016-10-11 19:50 UTC, enthusiastick commented on app/views/recipes/show.html.erb
> +    <br>
Also, if you're going to use `<br />` tags (which, Jesse is right, you should avoid), at least make them self-closing.

2016-10-11 19:51 UTC, enthusiastick commented
Train that hound.

![selfie-0](http://i.imgur.com/cEcavqD.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

2016-10-11 19:51 UTC, merged